server:
  port: 8085

jasypt:
  encryptor:
    password: Lke7Uy7eDgMn8BnQ
spring:
  application:
    name: shardingphere
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:
    username: ENC()
    password: ENC()

